version: '3.8'

services:
  redis-cluster-init:
    build: .
    image: redis-cluster
    container_name: redis-cluster
    network_mode: "host"
#    depends_on:
#      - redis-node-0
#      - redis-node-1
#      - redis-node-2
#      - redis-node-3
#      - redis-node-4
#      - redis-node-5
    environment:
      - 'REDISCLI_AUTH=redis2021'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=192.168.68.197'
      - 'REDIS_NODES_PORT=7000 7001 7002 7003 7004 7005'  # todo
      - 'REDIS_CLUSTER_CREATOR=yes'
