version: '3'
services:
  zoo1:
    build: .
    image: peaksong/zookeeper:3.6.2
    restart: always
    container_name: zoo1
    hostname: zoo1
    ports:
      - "21000:2181"
    environment:
      ZOO_MY_ID: 111
      ZOO_SERVERS: server.111=zoo1:2888:3888 server.222=zoo2:2888:3888 server.333=zoo3:2888:3888
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 5
      ZOO_SYNC_LIMIT: 2
      ZOO_MAX_CLIENT_CNXNS: 60
    volumes:
      - /D/docker/kafka_cluster/zookeeper/zoo1/data:/data
      - /D/docker/kafka_cluster/zookeeper/zoo1/log:/datalog

  zoo2:
    build: .
    image: peaksong/zookeeper:3.6.2
    restart: always
    container_name: zoo2
    hostname: zoo2
    ports:
      - "21001:2181"
    environment:
      ZOO_MY_ID: 222
      ZOO_SERVERS: server.111=zoo1:2888:3888 server.222=zoo2:2888:3888 server.333=zoo3:2888:3888
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 5
      ZOO_SYNC_LIMIT: 2
      ZOO_MAX_CLIENT_CNXNS: 60
    volumes:
      - /D/docker/kafka_cluster/zookeeper/zoo2/data:/data
      - /D/docker/kafka_cluster/zookeeper/zoo2/log:/datalog

  zoo3:
    build: .
    image: peaksong/zookeeper:3.6.2
    restart: always
    container_name: zoo3
    hostname: zoo3
    ports:
      - "21002:2181"
    environment:
      ZOO_MY_ID: 333
      ZOO_SERVERS: server.111=zoo1:2888:3888 server.222=zoo2:2888:3888 server.333=zoo3:2888:3888
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 5
      ZOO_SYNC_LIMIT: 2
      ZOO_MAX_CLIENT_CNXNS: 60
    volumes:
      - /D/docker/kafka_cluster/zookeeper/zoo3/data:/data
      - /D/docker/kafka_cluster/zookeeper/zoo3/log:/datalog