version: '3.5'

services:
  rmqnamesrv:
    image: rocketmq:4.9.1
    container_name: rmqnamesrv
    ports:
      - "9876:9876"
    volumes:
      - /home/peaksong/docker_vol/rocketmq/rmqs/logs:/home/rocketmq/logs
      - /home/peaksong/docker_vol/rocketmq/rmqs/store:/home/rocketmq/store
    environment:
      JAVA_OPT_EXT: "-Duser.home=/home/rocketmq -Xms512M -Xmx512M -Xmn128m"
    command: ["sh","mqnamesrv"]
    networks:
        rmq:
          aliases:
            - rmqnamesrv

  rmqbroker:
    image: rocketmq:4.9.1
    container_name: rmqbroker
    ports:
      - "10909:10909"
      - "10911:10911"
    volumes:
      - /home/peaksong/docker_vol/rocketmq/rmq/logs:/home/rocketmq/logs
      - /home/peaksong/docker_vol/rocketmq/rmq/store:/home/rocketmq/store
      - /home/peaksong/docker_vol/rocketmq/broker.conf:/etc/rocketmq/broker.conf
    environment:
        JAVA_OPT_EXT: "-Duser.home=/home/rocketmq -Xms512M -Xmx512M -Xmn128m"
    command: ["sh","mqbroker","-c","/etc/rocketmq/broker.conf","-n","rmqnamesrv:9876","autoCreateTopicEnable=true"]
    depends_on:
      - rmqnamesrv
    networks:
      rmq:
        aliases:
          - rmqbroker

  rmqconsole:
    image: styletang/rocketmq-console-ng
    container_name: rmqconsole
    ports:
      - "8180:8080"
    environment:
        JAVA_OPTS: "-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - rmqnamesrv
    networks:
      rmq:
        aliases:
          - rmqconsole

networks:
  rmq:
    name: rmq
    driver: bridge
