version: '3.3'

services:
  kafka0:
    image: wurstmeister/kafka
    container_name: kafka0
    ports:
      - 9092:9092
    external_links:
      - zoo1
      - zoo2
      - zoo3
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.175.98
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.175.98:9092
#      KAFKA_LISTENERS: PLAINTEXT://kafka0:9092
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2181,zoo3:2181"
      KAFKA_BROKER_ID: 0
    volumes:
      - /D/docker/kafka_cluster/kafka/kafka0/data:/data
      - /D/docker/kafka_cluster/kafka/kafka0/log:/datalog
    networks:
      zookeeper_zoo:
        ipv4_address: 172.20.0.10

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    ports:
      - 9093:9092
    external_links:
      - zoo1
      - zoo2
      - zoo3
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.175.98
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.175.98:9093
#      KAFKA_LISTENERS: PLAINTEXT://kafka1:9093
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2181,zoo3:2181"
      KAFKA_BROKER_ID: 1
    volumes:
      - /D/docker/kafka_cluster/kafka/kafka1/data:/data
      - /D/docker/kafka_cluster/kafka/kafka1/log:/datalog
    networks:
      zookeeper_zoo:
        ipv4_address: 172.20.0.11

  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    ports:
      - 9094:9092
    external_links:
      - zoo1
      - zoo2
      - zoo3
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.175.98
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.175.98:9094
#      KAFKA_LISTENERS: PLAINTEXT://kafka2:9094
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2181,zoo3:2181"
      KAFKA_BROKER_ID: 2
    volumes:
      - /D/docker/kafka_cluster/kafka/kafka2/data:/data
      - /D/docker/kafka_cluster/kafka/kafka2/log:/datalog
    networks:
      zookeeper_zoo:
        ipv4_address: 172.20.0.12

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    restart: unless-stopped
    container_name: kafka-manager
    hostname: kafka-manager
    ports:
      - "9999:9000"
    links:            # 连接本compose文件创建的container
      - kafka1
      - kafka2
      - kafka0
    external_links:   # 连接本compose文件以外的container
      - zoo3
      - zoo1
      - zoo2
    environment:
      ZK_HOSTS: "zoo1:2181,zoo2:2181,zoo3:2181"
      TZ: CST-8
    networks:
      zookeeper_zoo:
        ipv4_address: 172.20.0.99

networks:
  zookeeper_zoo:
    external: true