version: '3.3'

services:
  kafka0:
    image: 'bitnami/kafka:2.8.0'
    container_name: kafka0
    ports:
      - 9092:9092
    external_links:
      - zoo1
      - zoo2
      - zoo3
    environment:
      ALLOW_PLAINTEXT_LISTENER: true
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://192.168.175.98:9092
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2181,zoo3:2181"
      KAFKA_BROKER_ID: 0
    volumes:
      - /D/docker/kafka_cluster/kafka/kafka0/data:/data
      - /D/docker/kafka_cluster/kafka/kafka0/log:/datalog
    networks:
      zookeeper_zoo:
        ipv4_address: 172.20.0.10

  kafka1:
    image: 'bitnami/kafka:2.8.0'
    container_name: kafka1
    ports:
      - 9093:9092
    external_links:
      - zoo1
      - zoo2
      - zoo3
    environment:
      ALLOW_PLAINTEXT_LISTENER: true
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://192.168.175.98:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9093
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2181,zoo3:2181"
      KAFKA_BROKER_ID: 1
    volumes:
      - /D/docker/kafka_cluster/kafka/kafka1/data:/data
      - /D/docker/kafka_cluster/kafka/kafka1/log:/datalog
    networks:
      zookeeper_zoo:
        ipv4_address: 172.20.0.11

  kafka2:
    image: 'bitnami/kafka:2.8.0'
    container_name: kafka2
    ports:
      - 9094:9092
    external_links:
      - zoo1
      - zoo2
      - zoo3
    environment:
      ALLOW_PLAINTEXT_LISTENER: true
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://192.168.175.98:9094
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9094
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2181,zoo3:2181"
      KAFKA_BROKER_ID: 2
    volumes:
      - /D/docker/kafka_cluster/kafka/kafka2/data:/data
      - /D/docker/kafka_cluster/kafka/kafka2/log:/datalog
    networks:
      zookeeper_zoo:
        ipv4_address: 172.20.0.12

  cmak:
    image: 'mailbyms/cmak'
    container_name: cmak
    ports:
      - "9999:9000"
    environment:
      ZK_HOSTS: "zoo1:2181,zoo2:2181,zoo3:2181"
      KAFKA_MANAGER_AUTH_ENABLED: true
      KAFKA_MANAGER_USERNAME: admin
      KAFKA_MANAGER_PASSWORD: Lucky2021
    links:
      - kafka0
      - kafka1
      - kafka2
    external_links:
      - zoo1
      - zoo2
      - zoo3
    healthcheck:
      test: curl -f http://127.0.0.1:9000/api/health || exit 1
    restart: unless-stopped
    networks:
      zookeeper_zoo:
        ipv4_address: 172.20.0.99

networks:
  zookeeper_zoo:
    external: true