version: '2'
services:

  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_BROKE_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
